// apps/threejs-demos/advanced/18-tres/App.vue
<script setup>
import { Suspense } from 'vue';
import { TresCanvas } from '@tresjs/core';
import { OrbitControls, Environment } from '@tresjs/cientos';
import HelmetModel from './HelmetModel.vue';
import { DEMO_BG_CSS } from '../../shared/constants.js';
</script>

<template>
  <div class="tres-app">
    <header class="bar">
      <a href="/">← Demos</a>
      <span>进阶 18 · Vue 3 + TresJS · 声明式 3D</span>
    </header>
    <div class="canvas-wrap">
      <TresCanvas :clear-color="DEMO_BG_CSS" :dpr="[1, 2]">
        <TresPerspectiveCamera :position="[0, 0.5, 4]" :fov="45" />
        <OrbitControls make-default enable-damping :min-distance="1.5" :max-distance="12" />
        <TresAmbientLight :intensity="0.25" />
        <TresDirectionalLight :position="[5, 8, 5]" :intensity="0.9" />
        <Suspense>
          <Environment preset="sunset" :background="false" />
        </Suspense>
        <HelmetModel />
      </TresCanvas>
    </div>
    <div class="panel">
      <strong>Tres 要点</strong>
      <p class="hint">组件即 Object3D · GLTFModel / cientos · 与 R3F 对照（同一篇文档 18）</p>
    </div>
  </div>
</template>

<style scoped>
.tres-app { height: 100vh; display: flex; flex-direction: column; background: #0f1117; }
.canvas-wrap { flex: 1; min-height: 0; position: relative; }
.canvas-wrap :deep(canvas) { display: block; width: 100% !important; height: 100% !important; }
.hint { margin-top: 8px; font-size: 12px; color: #8b949e; line-height: 1.5; }
</style>

// apps/threejs-demos/advanced/18-r3f/App.jsx
/** 进阶 18 · React Three Fiber · docs/3d/threejs/advanced/18-r3f-tres.md */
import { Suspense } from 'react';
import { Canvas } from '@react-three/fiber';
import { OrbitControls, Environment } from '@react-three/drei';
import { HelmetModel } from './HelmetModel.jsx';
import { DEMO_BG_CSS } from '../../shared/constants.js';

export default function App() {
  return (
    <div className="r3f-app">
      <header className="bar">
        <a href="/">← Demos</a>
        <span>进阶 18 · React + R3F · 声明式 3D</span>
      </header>
      <div className="r3f-canvas">
        <Canvas
          camera={{ position: [0, 0.5, 4], fov: 45 }}
          dpr={[1, 2]}
          gl={{ antialias: true, powerPreference: 'high-performance' }}
        >
          <color attach="background" args={[DEMO_BG_CSS]} />
          <ambientLight intensity={0.25} />
          <directionalLight position={[5, 8, 5]} intensity={0.9} />
          <HelmetModel />
          <OrbitControls
            makeDefault
            enableDamping
            minDistance={1.5}
            maxDistance={12}
            maxPolarAngle={Math.PI * 0.48}
          />
          <Suspense fallback={null}>
            <Environment preset="sunset" background={false} />
          </Suspense>
        </Canvas>
      </div>
      <div className="panel">
        <strong>R3F 要点</strong>
        <p className="status" style={{ marginTop: 8 }}>
          Canvas + loadGLTF + drei Environment · 与 Tres 对照（文档 18）
        </p>
      </div>
    </div>
  );
}
