// apps/threejs-demos/advanced/18-r3f/HelmetModel.jsx
import { useEffect, useState } from 'react';
import { useThree } from '@react-three/fiber';
import { loadGLTF, normalizeRoot, fitCameraToObject } from '../../shared/loadModel.js';
import { MODELS } from '../../shared/constants.js';

export function HelmetModel() {
  const { camera, controls } = useThree();
  const [model, setModel] = useState(null);

  useEffect(() => {
    let alive = true;
    loadGLTF(MODELS.helmet).then((gltf) => {
      if (!alive) return;
      const root = gltf.scene;
      normalizeRoot(root, 2.5);
      setModel(root);
      if (camera) fitCameraToObject(camera, controls, root);
    });
    return () => { alive = false; };
  }, [camera, controls]);

  return model ? <primitive object={model} /> : null;
}

// apps/threejs-demos/advanced/18-tres/HelmetModel.vue
<script setup>
import { onMounted, onUnmounted } from 'vue';
import { useTres } from '@tresjs/core';
import { loadGLTF, normalizeRoot, fitCameraToObject } from '../../shared/loadModel.js';
import { MODELS } from '../../shared/constants.js';

const { scene, camera } = useTres();
let model = null;

onMounted(async () => {
  const gltf = await loadGLTF(MODELS.helmet);
  model = gltf.scene;
  normalizeRoot(model, 2.5);
  scene.value.add(model);
  if (camera.value) fitCameraToObject(camera.value, null, model);
});

onUnmounted(() => {
  model?.removeFromParent();
});
</script>

<template></template>
